config/routes.rb
OBDComm::Application.routes.draw do
  get "analytics/create"
  match "analytics/create" => "analytics#create", :via => :post
  
  get "analytics/show"
  get "analytics/index"
  match "/analytics" => "analytics#index"

  get "static_pages/community_map"
  match "/map" => "static_pages#community_map"
  
  get "static_pages/help"
  match "/help" => "static_pages#help"
  
  get "static_pages/landing"
  
  get "static_pages/badges"
  match "/badges" => "static_pages#badges"
  
  get "static_pages/scoreboard"
  match "/scoreboard" => "static_pages#scoreboard"
  
  get "static_pages/auth"
  match "/auth" => "static_pages#auth"
  
  get "measurement/create"
  match '/measurement/create' => 'measurement#create', :via => :post
  
  get "measurement/show"
  match "/measurement/:id" => "measurement#show"

  get "trip/show_static_trip"
  
  get "trip/show_single_trip"
  get "trip/show"

  get "trip/show_abstract_trip"
  match "/trip/abstract" => "trip#abstract"
  
  get "trip/abstract"
  match "/trip/abstract/:id" => "trip#show_abstract_trip"
  
  match "/trip/show/:id" => "trip#show_single_trip"
  
  get "/trip/compare"

  get "trip/create"
  match '/trip/create' => 'trip#create', :via => :post

  root :to => 'static_pages#landing'

  mount CommunityEngine::Engine => "/"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < BaseController
  
  #before_filter force_ssl, :only => [:auth]
  before_filter :require_group_2, :only => [:community_map]
  before_filter :require_group_3, :only => [:scoreboard, :badges]
  before_filter :track_action

  def community_map
      gon.user = current_user.id
      gon.user_group = current_user.group
      gon.params = params
    render :layout => "fullmap"
  end
  
  def auth
    authenticate_or_request_with_http_basic do |username, password|
      if user = User.find_by_login(username)
        response.headers['Auth'] = 'Password incorrect'
        if user.valid_password?(password)
          response.headers['Auth'] = 'Credentials correct'
          response.headers['Token'] = user.single_access_token
        end
      else
        response.headers['Auth'] = 'Username incorrect'
        false
      end
    end
  end
  
  def help
  end
  
  def badges
    gon.user = current_user.id
      gon.params = params
    if current_user.group == 3 || current_user.group == 0
      @badgesList = Hash.new(0)
      

      if params.has_key?(:user)
        @trips = User.find_by_id(params[:user]).trips.scoped.page(params[:page]).per(5).order('created_at DESC')
        User.find_by_id(params[:user]).badges.each do |v|
          @badgesList[v.id] += 1
        end
      else
        @trips = current_user.trips.scoped.page(params[:page]).per(5).order('created_at DESC')
        current_user.badges.each do |v|
          @badgesList[v.id] += 1
        end
      end
      
      render :layout => "trips"
    else
      redirect_to login_url
    end
  end

  def scoreboard
    gon.user = current_user.id
      gon.params = params
    #All Measurements, now do something with it!
    @measurements = Measurement.all
    render :layout => "trips"
  end
  
  def landing
    #if logged_in?
      #redirect_to "#{config.root}/trip/show"
    #else
    render :layout => "landing"
    #end
  end

  
  private
    def track_action
      if current_user != nil      
        Analytics.new(:user_id => current_user.id, :action => action_name, :url => "/static_pages/#{action_name}/", :description => params.to_json, :group => current_user.group, :category => "").save
      end
    end

    def require_group_2
      unless current_user.group == 2 || current_user.group == 0
        redirect_to login_url
      end
    end
    def require_group_3
      unless current_user.group == 3 || current_user.group == 0
        redirect_to login_url
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_menu_item.html.haml
- if current_user.group == 2 || current_user.group == 0
  - if current_page?(map_path)
    - css_class = 'active'
  - else
    - css_class = 'inactive'
    
  %li{:class => css_class}= link_to :community_map.l, map_path

- if current_user.group == 3 || current_user.group == 0
  - if current_page?(badges_path)
    - css_class = 'active'
  - else
    - css_class = 'inactive'
    
  %li{:class => css_class}= link_to :badges.l, badges_path

- if current_user.group == 3 || current_user.group == 0
  - if current_page?(scoreboard_path)
    - css_class = 'active'
  - else
    - css_class = 'inactive'
    
  %li{:class => css_class}= link_to :scoreboard.l, scoreboard_path

- if current_page?(help_path)
  - css_class = 'active'
- else
  - css_class = 'inactive'
  
%li{:class => css_class}= link_to :help.l, help_path

app/views/static_pages/badges.html.erb
<% @page_title = "Badges" %>
<!-- Modal -->
<div id="badgesModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Verfügbare Badges</h3>
  </div>
  <div class="modal-body">
    <ul>
      <% Merit::Badge.all.each do |b| %>
        <li>
          <a rel="tooltip" data-placement="right" title="Du erhältst <%= b.custom_fields[:points] %> Punkte!"><%= image_tag "Badges/#{b.custom_fields[:image]}", size: "28x28" %>
          <%= b.description %></a>
        </li>
      <% end %>
  </ul>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<h1>Zuletzt hochgeladene Fahrten</h1>
<% if @trips.blank? %>
    <p>Keine Fahrten zum Anzeigen vorhanden.</p>
<% else %>
  <div class="row">
    <div class="span10">
      <%= paginate @trips %>
        <!--Loop through all the trips and printem-->
        <% for @trip in @trips do%>
          <div class="row well">
            <div class="span4">
              <%= image_tag("/assets/trips/#{@trip.id}.png", size: "300x300") %>
              
            </div>
            <div class="span6 listing">
              <div class="row">
                <%= "#{@trip.getTripLength} Kilometers driven from #{Geocoder.search(@trip.measurements.first.latlon.y.to_s + "," + @trip.measurements.first.latlon.x.to_s).first.address} to #{Geocoder.search(@trip.measurements.last.latlon.y.to_s + "," + @trip.measurements.last.latlon.x.to_s).first.address} on #{@trip.measurements.first.recorded_at.strftime("%a, %d %B %Y")} at #{@trip.measurements.first.recorded_at.strftime("%H:%M %P")}" %>
              </div>
              <div class="row">
                <div class="span">
                  <h4 class="muted">DISTANZ</h4>
                  <p><i class="icon-globe"> </i><%= @trip.getTripLength %> Km</p>
                </div>
                <div class="span">
                  <h4 class="muted">Standzeit</h4>
                  <p><i class="icon-fire"> </i><%= '%.0f' % (@trip.measurements.where(:speed => 0).count * 5 / 60) %> min</p>
                </div> 
                <div class="span">
                  <h4 class="muted">MAX U/MIN</h4>
                  <p><i class="icon-fire"> </i><%= '%.0f' % (@trip.measurements.maximum(:rpm)) %></p>
                </div>
                <div class="span">
                  <h4 class="muted">Verbrauch</h4>
                  <p><i class="icon-fire"> </i><%= '%.2f' % (@trip.getAvgConsumption) %> l/100 km</p>
                </div>
                <div class="span">
                  <h4 class="muted">CO2</h4>
                  <p><i class="icon-fire"> </i><%= '%.2f' % (@trip.getAvgCo2) %> kg/100 km</p>
                </div>   
              </div>
              <div class="row">
                <h4>Verdiente Badges: </h4>
                <ul>
                  <% if @trip.badges.empty? %>
                    <p>Keine Badges erhalten diese Fahrt.</p>
                  <% else %>
                    <% @trip.badges.each do |badge| %>
                      <% @description = "#{badge[0].custom_fields[:points]}" + " Punkte für: #{badge[0].description}" %>
                      <li><a rel="tooltip" data-placement="left" data-original-title="<%= @description %>" ><%= image_tag "Badges/#{badge[0].custom_fields[:image]}", size: "30x30" %> <%= badge[0].name %></a></li>
                    <%end%>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>     
        <%end%> 
    </div>
    <div class="span2">
      <% unless Merit::Score.top_scored.to_json.length == 2 %>
        <% progress = (current_user.points) / ((Merit::Score.top_scored[0]["sum_points"].to_f)/100) %>
      <% end %>
      <%= progress_bar(progress, :color => 'blue', :rounded => true) %> 
      <h4><%= current_user.points %> Points</h4>
      <h2>Verdiente Badges:</h2>
      <a href="#badgesModal" data-toggle="modal"><i class="icon-plus-sign"></i> Verfügbare Badges</a>
      <% @badgesList.each do |k, v| %>
        <% @description = "#{Merit::Badge.get(k).custom_fields[:points]}" + " Punkte für: #{Merit::Badge.get(k).description}" %>
        <h4><a rel="tooltip" data-placement="left" data-original-title="<%= @description %>" ><%= image_tag "Badges/#{Merit::Badge.get(k).custom_fields[:image]}", size: "50x50" %> x<%= v %></a></h4>
      <%end%>
    </div>
  </div>
<%end%>
      

app/views/static_pages/community_map.html.erb
<% @page_title = "Karte" %>
<div class="smallmap" id="map">
  <div class="sensorswitch">
	  <div class="btn-group dropup">
	    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
	      Sensor
	      <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	        <li>
	          <a id="change-sensor-avg-consumption" href="#">Durchschnittlicher Verbrauch</a>
	        </li>
	        <li>
	          <a id="change-sensor-avg-rpm" href="#">Durchschnittliche Umdrehungen</a>
	        </li>
	        <li>
	          <a id="change-sensor-avg-speed" href="#">Durchschnittliche Geschwindigkeit</a>
	        </li>
	        <li>
	          <a id="change-sensor-max-speed" href="#">Max Geschwindigkeit</a>
	        </li>
	        <li>
	          <a id="change-sensor-avg-standing-time" href="#">Durchschnittliche Standzeit</a>
	        </li>
	        <li>
	          <a id="change-sensor-avg-co2" href="#">Durchschnittliche CO2 Emissionen</a>
	        </li>
	    </ul>
  	</div>
  	<div class="well legend">
	  		<h4>Legende</h4>
	  		<p id="legend_description">Durchschnittliche Geschwindigkeit</p>
	  		<img id="legend_image" src="http://giv-dueren.uni-muenster.de:8080/geoserver/OBDComm/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=OBDComm:osm_roads&style=avg_speed&FORMAT=image/png&transparent=true&LEGEND_OPTIONS=forceRule:True;dx:0.2;dy:0.2;mx:0.2;my:0.2;fontStyle:borderColor:0000ff;border:true;fontColor:000000;fontSize:14" ></img>
	  </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% @page_title = "Hilfe" %>
<h4 class="muted">Worum geht es bei der Case Study?</h4>
<p>Vielen Dank erst einmal für deine Mithilfe als Tester! Diese Studie wird im Rahmen einer Master Arbeit am Institut für Geoinformatik der WWU Münster durchgeführt. Im Rahmen eines Studienprojekts wurde diesen Sommer von ca. 20 Studenten eine Android App und ein Web Portal entwickelt, mit dem es möglich ist Sensor Daten aus Autos aufzuzeichnen. Diese Webseite und die App die du als Tester bekommst basiert auf den Ergebnissen von diesem Seminar.</p>
<p>Die Infrastruktur (App, Webportal, Server) funktionieren also schon und werden in einem anderen Kontext auf ihre Funktion und Fehler hin getestet. Die Studie an der du teil nimmst soll also kein Beta-Test sein in dem es darum geht Fehler in der Software zu finden, sondern darum das End-Produkt unter normalen Umständen zu testen. Das heißt es soll einfach von Menschen, die nicht an der Entwicklung mitgewirkt haben, im normalen Leben eingesetzt werden.</p>

<h4 class="muted">Wie läuft die Case Study ab?</h4>
<p>Es gibt ca. 10 Tester, die sich alle auf dieser Webseite registrieren. Jeder Tester ist in einer anderen Gruppe. Pro Gruppe werden unterschiedliche Funktionen der Webseite freigeschaltet, damit diese isoliert von einander getestet werden können. Wöchentlich werden diese Gruppen rotiert.</p>
<p>Das heißt für dich: Jede Woche bekommst du hier neue Funktionen freigeschaltet, die du ausprobieren kannst.</p>
<p>Jeder Tester erhält einen OBD Stecker, der im Auto angebracht werden kann sowie eine Android App mit der Autofahrten aufgenommen werden können. Ab dem <b>8. August</b> werden die ersten Funktionen dann freigeschaltet und alle Tester können loslegen.</p>
<p><b>Wichtig:</b>
	<ul>
		<li>Alles ist und bleibt anonym! Alle Daten werden nach der Studie gelöscht.</li>
		<li>Benutzt das App und das Web-Portal so oft und viel ihr wollt!</li>
		<li>Zögert nicht uns zu kontaktieren wenn ihr Fragen habt.</li>
	</ul>
</p>

<h4 class="muted">An wen wende ich mich wenn ich Fragen habe?</h4>
<p>Schreibe einfach eine kurze Mail an obd-studie@gmx.de. Die Mail wird so schnell wie möglich beantwortet.</p>

<h4 class="muted">Hilfe das App stürzt dauernd ab!</h4>
<p>Das Problem ist leider bekannt, konnte aber nicht im Vorfeld behoben werden. Falls das App abstürzt einfach neu starten und nochmal probieren. Falls gar nichts mehr geht muss leider manchmal der Bluetooth Adapter aus dem Auto ausgesteckt und wieder eingesteckt werden und das Handy neu mit dem Adapter gekoppelt (verbunden) werden, um das Problem zu lösen.</p>

<h4 class="muted">Ich habe einen Fehler gefunden</h4>
<p>Da diese Studie kein Beta Test ist, sind kleinere Fehler nicht so wichtig. Ihr könnt sie uns dennoch mitteilen wenn ihr möchtet (Mail an obd-studie@gmx.de). Falls du allerdings einen Fehler gefunden hast, der dich daran hindert die App oder das Web-Portal weiterhin sinnvoll zu nutzen, schicke uns bitte umgehend eine Mail damit das Problem behoben werden kann!</p>

<h4 class="muted">Einrichten der App</h4>
<center><img src="assets/help/bt.png" height="20%" width="20%"></img></center><br>

<p>Bevor die App benutzt werden kann muss das Handy mit dem OBD Bluetooth Adapter im Auto gekoppelt werden. Dazu muss in den Handy Einstellungen Bluetooth aktiviert werden. Im Bluetooth Menü kann dann der Adapter mit dem Namen "OBD II" ausgewählt werden. Das Passwort zum Koppeln ist "1234". Sobald der Adapter gekoppelt ist, verbindet sich das Handy automatisch dazu sobald es in Reichweite ist. Sollte der Adapter nicht auffindbar sein, kann es sein, dass der Motor angeschaltet sein muss, damit der Adapter gefunden werden kann.</p>
<br>
<p>Nach dem ersten Starten müssen in der App einige Einstellungen vorgenommen werden:</p>
<center><img src="assets/help/dash.png" height="20%" width="20%"></img>  <img src="assets/help/car.png" height="20%" width="20%"></img></center>
<br>

<p>Es MUSS ein Auto eingestellt sein, dazu kann ein neues erstellt werden oder aus einer Liste ein bestehendes ausgewählt werden. Für die Case Study spielt es keine Rolle welches Auto ausgewählt ist, d.h. es kann irgendein Auto ausgewählt werden. Es muss nur ein Auto eingetragen sein damit das App funktioniert. Dazu tippe auf den Stift unter "Aktuelles Auto".</p>
<br>

<center><img src="assets/help/menu.png" height="20%" width="20%"></img>  <img src="assets/help/settings.png" height="20%" width="20%"></img></center>
<br>

<p>In der App selber kommt man durch wischen von links nach rechts oder über das Logo an das Menü. Im Menü kann man sich mit dem Benutzernamen und Passwort, welche auch auf dieser Seite verwendet wird, einloggen. Dort muss auch unter Einstellungen der Hubraum des Autos eingestellt werden, damit der Verbrauch korrekt berechnet werden kann. Außerdem sollte hier ein Bluetooth Adapter ausgewählt werden (Der vorher schon mit dem Handy gekoppelt wurde).</p>
<br>

<center><img src="assets/help/tracks.png" height="20%" width="20%"></img></center>
<br>

<p>In der Ansicht "Meine Fahrten" werden auf dem Handy gespeicherte Fahrten angezeigt. Sobald diese Hochgeladen sind, werden sie automatisch aus der Liste entfernt. Zum Hochladen bitte auf den Pfeil oben rechts tippen.</p>

<h4 class="muted">Hinweise zur App</h4>
<ul>
	<li>Normales Vorgehen:
		<ul>
			<li>1. Ins Auto setzen und Motor starten.</li>
			<li>2. Handy App starten und im Menü auf "Start" tippen</li>
			<li>3. Das Handy sagt "Messung gestartet" und im unteren Bereicht sollten Zahlen eingeblendet werden. Dann läuft die Messung.</li>
			<li>4. Nach Beendigen der Fahrt im Menü auf "Stop drücken". </li>
			<li>5. Unter "Meine Fahrten" auf Hochladen tippen. In der Statusleiste wird angezeigt, ob das Hochladen erfolgreich war.</li>
		</ul>
	<li>Die App kann ab und zu mal abstürzen. Dies ist nicht weiter schlimm, einfach die App neu starten.</li>
	<li>Falls in der App durch einen Absturz eine leere Fahrt erstellt wurde kann diese über das Mülleimer-Symbol unter "Meine Fahrten" gelöscht werden. (Leere Fahrten können zu Fehlern beim Hochladen führen)
	<li>Es gibt einige Optionen unter "Einstellungen". "Automatische Verbindung" sowie "Automatisch hochladen" und "Nur im WLAN hochladen" funktionieren noch nicht.</li>
	</ul> 

app/views/static_pages/landing.html.erb
<header class="jumbotron subhead" id="overview">
  <div id="map" class="smallmap"></div> 
</header>


<div class="container marketing">
  <div class="apply-wrapper text-center" id="apply-wrapper">
    <div class="apply-box">
        <h3>Hinweis:</h3>
            <div>
              <b>Diese Seite wird nur für eine Case-Study im Rahmen einer Masterarbeit am Institut für Geoinformatik an der WWU Münster genutzt. Falls Sie durch eine Zeitungsanzeige auf uns aufmerksam geworden sind folgen Sie bitte diesem <a href="http://giv-dueren.uni-muenster.de/anzeige.html" >Link</a>.<br> Für zusätzliche Informationen kontaktieren Sie uns bitte:</b><br>
              <a href="mailto:obd-studie@gmx.de" class="btn btn-primary" data-ie="before" id="sign_in">Kontakt</a>
            </div><!-- end of apply facebook -->      
    </div><!-- end of footer headline -->
  </div>




  <ul class="nav nav-tabs center" id="nav-tabs">
    <li>
      <a href="#nav-tabs">Was wird benötigt?</a>
    </li >
    <li><a href="#featurettes">Was bekomme ich?</a></li>
</ul>
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="span4">
      <img src="assets/gauge.png">
      <h2>OBD2 Standard</h2>
      <p>In allen in Deutschland verfügbaren Autos seit 2004 ist ein OBD2 Anschluss verpflichtend. Mithilfe eines kleinen Bluetooth-Adapters ist es in allen diesen Autos möglich Werte wie z.B. den Verbrauch auszulesen.</p>
    </div><!-- /.span4 -->
    <div class="span4">
      <img src="assets/elm.jpg">
      <h2>Billige Hardware</h2>
      <p>Zur Nutzung des OBD2 Anschlusses ist lediglich ein sehr kostengünstiger Bluetooth Adapter nötig. Die meisten Adapter kosten zwischen 12 und 150 Euro.</p>
    </div><!-- /.span4 -->
    <div class="span4">
      <img src="assets/android.png"h>
      <h2>Android</h2>
      <p>Zur Übertragung der Daten vom Auto zu diesem Web Portal wird eine einfach zu bedienende Android App benötigt. Diese empfängt die Daten des Bluetooth Adapters und leitet diese an unseren Server weiter.</p>
    </div><!-- /.span4 -->
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette" id="featurettes">
    <div class="row" >
      <div class="span6">
        <img src="../assets/responsive.jpg" width="100%">
      </div>
      <div class="span6">
        <h2 class="featurette-heading">Fahrten Aufzeichnen <span class="muted"></span></h2>
        <p class="lead">Mithilfe der App und dieser Webseite ist es einfach Autofahrten aufzuzeichnen und hier abzuspeichern. Ihr seht dabei genaue Werte eurer Fahrt und des Autos. So kann z.B. der Benzinverbrauch und die dadurch entstandenen Kosten angezigt werden. Die Fahrt kann in einer interaktiven Karte betrachtet werden, es können aber auch Graphen und Fakten dargestellt werden.</p>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <div class="row" >
      <div class="span6">
        <h2 class="featurette-heading">Badges <span class="muted">Auszeichnungen und Punkte</span></h2>
        <p class="lead">Zum vorbildlichen Fahren motivieren sogenannte Badges, die pro Fahrt verliehen werden können. Fährt man z.B. besonders Spritsparend bekommt man eine Auszeichnung, und dem Fahrer werden Punkte gutgeschrieben. So kann man sich selbst mit anderen Fahrern vergleichen. </p>
      </div>
      <div class="span6">
        <img src="../assets/gamification.png" width="100%">
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <div class="row" >
      <div class="span6">
        <img src="../assets/comm.png" width="100%">
      </div>
      <div class="span6">
        <h2 class="featurette-heading">Community <span class="muted"></span></h2>
        <p class="lead">Die Daten, die beim Fahren produziert werden sind natürlich wichtig. Nicht nur für euch sondern auch für unsere Umwelt. So kann aus dem gesammelten Werten aller Fahrer eine CO2 Karte erstellt werden, oder wir können herausfinden auf welchen Strecken am meisten Benzin verbraucht wird. Dazu gibt es verschiedene interaktive Karten mit den gesammelten Daten aber auch mit den Persönlich Daten.</p>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

</div><!-- /.container -->

app/views/static_pages/scoreboard.html.erb
<% @page_title = "Punkte-Tafel" %>
<table class="table table-hover">
<thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Punkte</th>
    <th>Kilometer</th>
    <th>Verbrauch</th>
  </tr>
</thead>
<tbody>
  <% top = Merit::Score.top_scored %>
  <% for i in 0..(top.ntuples-1) do %>
    <% user = User.find_by_id(top[i]["user_id"]) %>
    <tr class="h">
      <td class="vmid"><%= i + 1 %>.</td>
      <td class="vmid"><%= link_to image_tag( user.avatar_photo_url(:medium), size: "100x100" ), user_path(user) %> <%= link_to user.login, user_path(user) %></td>
      <td class="vmid"><i class="icon-star"> <%= user.points %></td>
      <td class="vmid"><i class="icon-globe"> <%= user.mileage %> Km</td>
      <td class="vmid"><i class="icon-tint"> <%= '%.2f' % user.consumption %> l/100 km</td>
    </tr>
  <% end %>
</tbody>
</table>