config/routes.rb
OBDComm::Application.routes.draw do
  get "analytics/create"
  match "analytics/create" => "analytics#create", :via => :post
  
  get "analytics/show"
  get "analytics/index"
  match "/analytics" => "analytics#index"

  get "static_pages/community_map"
  match "/map" => "static_pages#community_map"
  
  get "static_pages/help"
  match "/help" => "static_pages#help"
  
  get "static_pages/landing"
  
  get "static_pages/badges"
  match "/badges" => "static_pages#badges"
  
  get "static_pages/scoreboard"
  match "/scoreboard" => "static_pages#scoreboard"
  
  get "static_pages/auth"
  match "/auth" => "static_pages#auth"
  
  get "measurement/create"
  match '/measurement/create' => 'measurement#create', :via => :post
  
  get "measurement/show"
  match "/measurement/:id" => "measurement#show"

  get "trip/show_static_trip"
  
  get "trip/show_single_trip"
  get "trip/show"

  get "trip/show_abstract_trip"
  match "/trip/abstract" => "trip#abstract"
  
  get "trip/abstract"
  match "/trip/abstract/:id" => "trip#show_abstract_trip"
  
  match "/trip/show/:id" => "trip#show_single_trip"
  
  get "/trip/compare"

  get "trip/create"
  match '/trip/create' => 'trip#create', :via => :post

  root :to => 'static_pages#landing'

  mount CommunityEngine::Engine => "/"
end

app/controllers/trip_controller.rb
class TripController < BaseController

  
  before_filter :login_required, :only => [:show]
  #before_filter :basic_auth, :only => [:create]
  before_filter :track_action, :only => [:show, :abstract, :compare, :show_single_trip, :show_abstract_trip]

  before_filter :require_group_1, :only => [:show, :show_single_trip]
  before_filter :require_group_1_or_2, :only => [:compare]
  before_filter :require_group_4, :only => [:abstract, :show_abstract_trip]

  uses_tiny_mce do
    {:only => [:show], :options => configatron.default_mce_options}
  end

  def show
    url = URI.parse('http://export.benzinpreis-aktuell.de/exportdata.txt?code=dCd47e7y1f6a43z')
    @fuel_prices = Net::HTTP.get(url).split(';')[2..5]

    gon.user_id = current_user.id
    gon.params = params
    if params.has_key?(:user)
      @trips = User.find_by_id(params[:user]).trips.scoped.page(params[:page]).per(5).order('created_at DESC')
    else
      @trips = current_user.trips.scoped.page(params[:page]).per(5).order('created_at DESC')
    end
    @action = "trip_" + action_name
    render :layout => "trips"
  end

  def abstract
    I18n.locale = "de"
    gon.user = current_user.id

    gon.params = params
    if params.has_key?(:user)
      @trips = User.find_by_id(params[:user]).trips.scoped.page(params[:page]).per(5).order('created_at DESC')
    else
      @trips = current_user.trips.scoped.page(params[:page]).per(5).order('created_at DESC')
    end
    render :layout => "trips"
  end

  def compare
    @action = action_name
    @tripA = Trip.find_by_id(params[:a])
    @tripB = Trip.find_by_id(params[:b])
    gon.user = current_user.id
    gon.user_group = current_user.group
    gon.params = params
    gon.measurementsMap1 = @tripA.measurements.order("recorded_at ASC")
    gon.measurementsMap2 = @tripB.measurements.order("recorded_at ASC")

    render :layout => "trips"
  end
  
  #used for ..\show\trip\:id
  def show_single_trip
    @action = action_name

    url = URI.parse('http://export.benzinpreis-aktuell.de/exportdata.txt?code=dCd47e7y1f6a43z')
    @fuel_prices = Net::HTTP.get(url).split(';')[2..5]

    if params.has_key?(:id)
      @trip = Trip.find_by_id(params[:id])
      gon.user = current_user.id
      gon.user_group = current_user.group
      gon.params = params
      gon.measurements = @trip.measurements.order("recorded_at ASC")

      gon.statistics = {"max_speed" => @trip.measurements.maximum(:speed), "max_rpm" => @trip.measurements.maximum(:rpm), "max_consumption" => @trip.measurements.maximum(:consumption)}
      render :layout => "trips"
    end
  end
  
  def show_abstract_trip
    @action = action_name
    if params.has_key?(:id)
      @trip = Trip.find_by_id(params[:id])
      gon.user = current_user.id
      gon.user_group = current_user.group
      gon.params = params
      gon.measurements = @trip.measurements

      gon.statistics = {"max_speed" => @trip.measurements.maximum(:speed), "max_rpm" => @trip.measurements.maximum(:rpm), "max_consumption" => @trip.measurements.maximum(:consumption)}
      render :layout => "trips"
    end
  end

  #used for making a map snapshot
  def show_static_trip
    if params.has_key?(:id)
      gon.measurements = Trip.find_by_id(params[:id]).measurements# @tripMeasurement.where("trip_id = ?",  @tripId)
    end
    render :layout => "trip_static"
  end


  def create
    @current_user = User.find_by_login_or_email(params[:user])
    #create empty trip to get an id to pass on to measurements
    @trip = Trip.new
    #@trip.save

    wgs84_proj4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'


    wgs84_factory = RGeo::Cartesian.factory(:srid => 4326)

    unless params[:import].nil?
      @trip.user_id = @current_user.id

      measurements = []
      params[:features].each { |feature| 
        coords = wgs84_factory.point(feature[:geometry][:coordinates][0],feature[:geometry][:coordinates][1])
        rpm = feature[:properties][:phenomenons][:Rpm][:value]
        iat = feature[:properties][:phenomenons][:'Intake Temperature'][:value]
        map = feature[:properties][:phenomenons][:'Intake Pressure'][:value]

        maf = 0
        if feature[:properties][:phenomenons][:'MAF'] != nil
          maf = feature[:properties][:phenomenons][:'MAF'][:value]
        else
          maf = feature[:properties][:phenomenons][:'Calculated MAF'][:value]
        end

        if @current_user.login == "dhudi" || @current_user.login == "Annette" || @current_user.login == "Josef"
          imap = rpm * (map - 70.0) / (iat + 273.0)
          if @current_user.login == "Annette" || @current_user.login == "Josef"
            imap = rpm * (map - 75.0) / (iat + 273.0)
          end
          
          maf = (imap / 120.0) * (80.0 / 100.0) * 1.995 * 28.97 / 8.317
          if maf < 0.0
            maf = 0.0
          end
        end

        speed = feature[:properties][:phenomenons][:Speed][:value]
        consumption = 0
        co2 = 0
        if speed > 0 
          consumption = (maf * 3355) / (speed * 100)
        else
          consumption = (maf * 3355) / 10000
        end

        #consumption = feature[:properties][:phenomenons][:Consumption][:value] #is in l/s
        if consumption > 50
          consumption = 50
        end

        co2 = consumption * 2.35 #gets kg/100 km
        recorded_at = feature[:properties][:time]

        if !measurements.empty? && (Time.parse(recorded_at) - measurements.last.recorded_at) > 15 
          m = Measurement.new(
            "recorded_at" => measurements.last.recorded_at + 15,
            "speed" => 0,
            "rpm" => 0,
            "maf" => 0, #is in g/s
            "iat" => 0,
            "map" => 0,
            "consumption" => 0,
            "co2" => 0,
            "latlon" => measurements.last.latlon,
            )
          measurements << m
        end

        m = Measurement.new(
          "recorded_at" => recorded_at,
          "speed" => speed,
          "rpm" => rpm,
          "maf" => maf, #is in g/s
          "iat" => iat,
          "map" => map,
          "consumption" => consumption,
          "co2" => co2,
          "latlon" => coords,
          )

        measurements << m
      }



      measurements.sort! { |a,b| a.recorded_at <=> b.recorded_at }
      Rails.logger.info "nach sort"
      measurements.each do  |m|
        @trip.measurements.new(
          "recorded_at" => m.recorded_at,
          "speed" => m.speed,
          "rpm" => m.rpm,
          "maf" => m.maf,
          "iat" => m.iat,
          "map" => m.map,
          "consumption" => m.consumption,
          "co2" => m.co2,
          "latlon" => m.latlon
          )
      end
      Rails.logger.info "vor respond to"



      respond_to do |format|
        if @trip.save

          if @trip.measurements.length > 4
            format.html { redirect_to @trip, notice: 'Trip successfully created.' }
            format.json { render json: @trip, status: :created}

            @exec = "/usr/bin/phantomjs/bin/phantomjs " +
                  "./app/assets/javascripts/phantom_snapshot.js " +
                  "http://" + configatron.app_host + "/trip/show_static_trip?id=#{@trip.id} " +
                  "./public/assets/trips/#{@trip.id}.png '#map'"
            thread = Thread.new{
              system(@exec)
            }
            thread.join
            
            #update user statistics
            Rails.logger.info "Updating User Statistics"
            Rails.logger.info 
            div = @trip.measurements.length + @current_user.measurement_count
            
            @current_user.update_attributes(:rpm => (((@current_user.rpm * @current_user.measurement_count) + (@trip.measurements.average(:rpm).to_f * @trip.measurements.length)) / div))
            @current_user.update_attributes(:speed => (((@current_user.speed * @current_user.measurement_count) + (@trip.measurements.average(:speed).to_f * @trip.measurements.length)) / div))
            @current_user.update_attributes(:consumption => (((@current_user.consumption * @current_user.mileage) + (@trip.getAvgConsumption * @trip.getTripLength)) / (@current_user.mileage + @trip.getTripLength)))
            @current_user.update_attributes(:standingtime => (@current_user.standingtime + (@trip.measurements.where(:speed => 0).count * 5)))
            @current_user.update_attributes(:co2 => (((@current_user.co2 * @current_user.mileage) + (@trip.getAvgCo2 * @trip.getTripLength)) / (@current_user.mileage + @trip.getTripLength)))
            @current_user.update_attributes(:total_co2 => (@current_user.total_co2 + (@trip.getTotalCo2)))
            @current_user.update_attributes(:total_consumption => (@current_user.total_consumption + (@trip.getTotalConsumption)))
            @current_user.update_attributes(:measurement_count => (@current_user.measurement_count + @trip.measurements.length))
            @current_user.update_attributes(:mileage => (@current_user.mileage + @trip.getTripLength))


            @trip.delay.integrateTrip
            #@trip.integrateTrip
          else 
            @trip.destroy
            format.json { render json: "Corrupted Trip Measurements", status: :created }
          end
        else
          format.html { render :layout => "trips" }
          format.json { render json: @trip.errors, status: :unprocessable_entity }
        end
      end
    else
      #create real trip from json here
      @trip = Trip.new(params[:trip])
      @trip.user_id = User.find_by_login_or_email(params[:user]).id
      #change trip_id in measurements
      @trip.measurements.each { |x|
        x.trip_id = @trip.id
      }
      respond_to do |format|
        if @trip.save
          format.html { redirect_to @trip, notice: 'Trip successfully created.' }
          format.json { render json: @trip, status: :created}
        else
          format.html { render :layout => "trips" }
          format.json { render json: @trip.errors, status: :unprocessable_entity }
        end
      end
    end

    
  end


  private

app/helpers/trip_helper.rb
module TripHelper
end

app/views/trip/_menu_item.html.haml
- if current_user.group == 1 || current_user.group == 0
  - if current_page?(trip_show_path)
    - css_class = 'active'
  - else
    - css_class = 'inactive'
    
  %li{:class => css_class}= link_to :my_trips.l, trip_show_path

- if current_user.group == 4 || current_user.group == 0
  - if current_page?(trip_show_abstract_trip_path)
    - css_class = 'active'
  - else
    - css_class = 'inactive'
    
  %li{:class => css_class}= link_to :trips.l, trip_abstract_path

app/views/trip/abstract.html.erb
<% @page_title = "Fahrten" %>
<div class="row">
	<h1>Übersicht</h1>
	<div class="row">
		<table class="table table-striped">
      <thead>
        <tr>
          <th><h4 class="muted">DISTANZ GESAMT</h4></th>
          <th><h4 class="muted">ANZAHL FAHRTEN</h4></th>
          <th><h4 class="muted">CO2 EMISSIONEN GESAMT</h4></th>
          <th><h4 class="muted">DURCHSCHNITTL. CO2</h4></th>
          <th><h4 class="muted">BENZINVERBRAUCH GESAMT</h4></th>
          <th><h4 class="muted">DURCHSCHNITTL. VERBRAUCH</h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><i class="icon-globe"> </i><%= current_user.mileage %> Km</td>
          <td><i class="icon-list"> </i><%= current_user.trips.length %></td> 
          <td><i class="icon-road"> </i><%= '%.2f' % (current_user.total_co2) %> kg</td>
          <td><img src="../../assets/icon_durchschnitt.gif"> <%= '%.0f' % current_user.co2 %> kg/100 km</td>
          <td><i class="icon-fire"> </i><%= '%.0f' % current_user.total_consumption %> Liter</td>
          <td><img src="../../assets/icon_durchschnitt.gif"> <%= '%.1f' % current_user.consumption %> l/100km</td>
        </tr>
      </tbody>
    </table>
	</div>
</div>

<div class="container">
	<h1>Zuletzt hochgeladene Fahrten</h1>
	<% if @trips.blank? %>
		<p>Keine Fahrten zum Anzeigen vorhanden.</p>
	<% else %>
		<%= paginate @trips %>
		<hr class="featurette-divider">
		<!--Loop through all the trips and printem-->
		<% for @trip in @trips do%>
			<div class="row well">
				<div class="span6">
					<div class="trip_info">
						<%= link_to image_tag("/assets/trips/#{@trip.id}.png"), "/trip/abstract/#{@trip.id}" %>
					</div>
				</div>
				<div class="span6 listing">
					<div class="row">
						<%= link_to "#{@trip.getTripLength} Kilometer von #{Geocoder.search(@trip.measurements.first.latlon.y.to_s + "," + @trip.measurements.first.latlon.x.to_s).first.address} nach #{Geocoder.search(@trip.measurements.last.latlon.y.to_s + "," + @trip.measurements.last.latlon.x.to_s).first.address} am #{I18n.l @trip.measurements.first.recorded_at, format: :literal_date} um #{I18n.l @trip.measurements.first.recorded_at, format: :time_ago}", "/trip/abstract/#{@trip.id}" %>
					</div>
					<div class="row">
						<div class="span2">
							<h4 class="muted">ENTFERNUNG</h4>
							<p><i class="icon-globe"> </i><%= @trip.getTripLength %> Km</p>
						</div>
						<div class="span2">
							<h4 class="muted">BENZINVERBRAUCH</h4>
							<p><i class="icon-fire"> </i><%= '%.2f' % (@trip.getTotalConsumption) %> Liter</p>
						</div>
						<div class="span2">
							<h4 class="muted">CO2 AUSSTOSS</h4>
							<p><i class="icon-leaf"></i> <%= '%.2f' % (@trip.getTotalCo2) %> kg</p>
						</div>			
					</div>
					<div class="row">
						<p>
							<% 
								overall_avg_co2 = User.where("co2 > 0").average(:co2).to_f 
								avg_co2_per = overall_avg_co2 / 100
								trip_avg_co2 = @trip.getAvgCo2
								smilie_text = ""	
							%>
							<%= 
								if overall_avg_co2 > 0 && trip_avg_co2 > 0
									if trip_avg_co2 < (overall_avg_co2 - (25 * avg_co2_per))
										smilie_text = "Wow! Die CO2 Werte dieser Fahrt sind um 25% besser als der Durchschnitt."
										image_tag "/assets/smilies/1.png", size: "70x70"
									elsif (overall_avg_co2 - (5 * avg_co2_per)) > trip_avg_co2 && trip_avg_co2 > (overall_avg_co2 - (25 * avg_co2_per))
										smilie_text = "Toll! Die CO2 Werte dieser Fahrt sind um 15% besser als der Durchschnitt."
										image_tag "/assets/smilies/2.png", size: "70x70"
									elsif (overall_avg_co2 + (5 * avg_co2_per)) > trip_avg_co2 && trip_avg_co2 > (overall_avg_co2 - (5 * avg_co2_per))
										smilie_text = "Die CO2 Werte dieser Fahrt sind super!"
										image_tag "/assets/smilies/3.png", size: "70x70"
									elsif (overall_avg_co2 + (5 * avg_co2_per)) < trip_avg_co2 && trip_avg_co2 < (overall_avg_co2 + (25 * avg_co2_per))
										smilie_text = "Ups! Die CO2 Werte dieser Fahrt sind um 15% schlechter als der Durchschnitt."
										image_tag "/assets/smilies/4.png", size: "70x70"
									elsif trip_avg_co2 > (overall_avg_co2 + (25 * avg_co2_per))
										smilie_text = "Oh nein! Die CO2 Werte dieser Fahrt sind um 25% schlechter als der Durchschnitt."
										image_tag "/assets/smilies/6.png", size: "70x70"
									end		
								end				
							%>
							<%= smilie_text %>
						</p>
					</div>
				</div>
			</div>
			<hr class="featurette-divider">			
		<%end%>
	<%end%>	
</div> <!-- end container -->

app/views/trip/compare.html.erb
<% @page_title = "Vergleich" %>
<div class="row">
	<div class="span6">
	  <h4>Fahrt von <span class="muted"><%= Geocoder.search(@tripA.measurements.first.latlon.y.to_s + "," + @tripA.measurements.first.latlon.x.to_s).first.address%></span> nach <span class="muted"><%= Geocoder.search(@tripA.measurements.last.latlon.y.to_s + "," + @tripA.measurements.last.latlon.x.to_s).first.address%></span></h4>
	</div>
	<div class="span6">
	  <h4>Fahrt von <span class="muted"><%= Geocoder.search(@tripB.measurements.first.latlon.y.to_s + "," + @tripB.measurements.first.latlon.x.to_s).first.address%></span> nach <span class="muted"><%= Geocoder.search(@tripB.measurements.last.latlon.y.to_s + "," + @tripB.measurements.last.latlon.x.to_s).first.address%></span></h4>
  </div>
</div>
<div class="row">
	<div class="span6">
		<div class="span1">
	    <p><i class="icon-globe"> </i> <abbr title="Distanz"><%= @tripA.getTripLength %> Km</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-time"> </i> <abbr title="Dauer"><%=(@tripA.measurements.last.recorded_at.to_i - @tripA.measurements.first.recorded_at.to_i) / 60 %> min</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-fire"></i> <abbr title="Durchschnittl. Verbrauch"> <%= '%.2f' % @tripA.getAvgConsumption.to_f %> L</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-pause"></i> <abbr title="Standzeit"><%= '%.0f' % (@tripA.measurements.where(:speed => 0).count * 5 / 60) %> min</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-random"></i> <abbr title="Durchschnittl. Geschwindigkeit"><%= '%.0f' % @tripA.measurements.average(:speed).to_f %> km/h</abbr></p>
	  </div>
	</div>
	<div class="span6">
		<div class="span1">
	    <p><i class="icon-globe"> </i> <abbr title="Distanz"><%= @tripB.getTripLength %> Km</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-time"> </i> <abbr title="Dauer"><%=(@tripB.measurements.last.recorded_at.to_i - @tripB.measurements.first.recorded_at.to_i) / 60 %> min</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-fire"></i> <abbr title="Durchschnittl. Verbrauch"> <%= '%.2f' % @tripB.getAvgConsumption.to_f %> L</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-pause"></i> <abbr title="Standzeit"><%= '%.0f' % (@tripB.measurements.where(:speed => 0).count * 5 / 60) %> min</abbr></p>
	  </div>
	  <div class="span1">
	    <p><i class="icon-random"></i> <abbr title="Durchschnittl. Geschwindigkeit"><%= '%.0f' % @tripB.measurements.average(:speed).to_f %> km/h</abbr></p>
	  </div>
  </div>
</div>
<div class="row">
	<div class="span6">
		<div class="row">
		  <div class="span6">
		  	<div id="map1"></div>
		  </div>
		</div>
		<div class="row">  	
			<div class="span6">
				<div id="chartContainerMap1" style="height: 250px; width: 100%;"></div>
			</div>
		</div>
		<div class="row">
		</div>
	</div>
	<div class="span6">
		<div class="row">
	  	<div class="span6">
	  		<div id="map2"></div>
	  	</div>
	  </div>
	  <div class="row">
	  	<div class="span6">
	  		<div id="chartContainerMap2" style="height: 250px; width: 100%;"></div>
	  	</div>
	  </div>
  </div>
</div>

app/views/trip/create.html.erb
<h1>Trip#create</h1>
<p>Find me in app/views/trip/create.html.erb</p>

app/views/trip/show.html.erb
<% @page_title = "Fahrten" %>
<div class="row" style="margin-left: -30px;">
	<h1>Übersicht</h1>
	<div class="span2">
		<h4 class="muted">DISTANZ</h4><br>
		<p><i class="icon-globe"> </i><%= current_user.mileage %> Km</p>
	</div>
	<div class="span2">
		<h4 class="muted">FAHRTEN</h4><br>
		<p><i class="icon-list"> </i><%= current_user.trips.length %></p>
	</div>
	<div class="span2">
		<h4 class="muted">STANDZEIT</h4><br>
		<p><i class="icon-pause"> </i><%= '%.2f' % (current_user.standingtime / 60.0 / 60.0) %> h</p>
	</div>
	<div class="span2">
		<h4 class="muted">DURCHSCHNITTL. GESCHWINDIGKEIT</h4>
		<p><img src="../../assets/icon_durchschnitt.gif"> </i><%= '%.0f' % current_user.speed %> Km/h</p>
	</div>
	<div class="span2">
		<h4 class="muted">DURCHSCHNITTL. UMDREHUNGEN</h4>
		<p><img src="../../assets/icon_durchschnitt.gif"> </i><%= '%.0f' % current_user.rpm %> Rpm</p>
	</div>
	<div class="span2">
		<h4 class="muted">DURCHSCHNITTL. VERBRAUCH</h4>
		<p><img src="../../assets/icon_durchschnitt.gif"> </i><%= '%.1f' % current_user.consumption %> l/100km</p>
	</div>
</div>

<div class="container">
	<h1>Zuletzt hochgeladene Fahrten</h1>
	<% if @trips.blank? %>
		<p>Keine Fahrten zum Anzeigen vorhanden.</p>
	<% else %>
		<%= paginate @trips %>
		<hr class="featurette-divider">
		<!--Loop through all the trips and printem-->
		<% for @trip in @trips do%>
			<div class="row well">
				<div class="span6">
					<div class="trip_info">
						<%= link_to image_tag("/assets/trips/#{@trip.id}.png"), "/trip/show/#{@trip.id}" %>
					</div>
				</div>
				<div class="span6 listing">
					<div class="row">
						<%= link_to "#{@trip.getTripLength} Kilometer von #{Geocoder.search(@trip.measurements.first.latlon.y.to_s + "," + @trip.measurements.first.latlon.x.to_s).first.address} nach #{Geocoder.search(@trip.measurements.last.latlon.y.to_s + "," + @trip.measurements.last.latlon.x.to_s).first.address} am #{I18n.l @trip.measurements.first.recorded_at, format: :literal_date} um #{I18n.l @trip.measurements.first.recorded_at, format: :time_ago}", "/trip/show/#{@trip.id}" %>
					</div>
					<div class="row">
						<div class="span2">
							<h4 class="muted">DISTANZ</h4>
							<p><i class="icon-globe"> </i><%= @trip.getTripLength %> Km</p>
						</div>
						<div class="span2">
							<h4 class="muted">BENZINVERBRAUCH</h4>
							<p><i class="icon-fire"> </i><%= '%.2f' % (@trip.getTotalConsumption) %> Liter = <%= '%.2f' % (@trip.getTotalConsumption * @fuel_prices[0].to_f) %>€</p>
						</div>
						<div class="span2">
							<h4 class="muted">CO2</h4>
							<p><i class="icon-leaf"></i> <%= '%.2f' % (@trip.getTotalCo2) %> kg</p>
						</div>			
					</div>
				</div>
			</div>
			<hr class="featurette-divider">			
		<%end%>
	<%end%>	
</div> <!-- end container -->

app/views/trip/show_static_trip.html.erb
<div id="map" class="smallmap"></div>